remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

title: [La Flor Blanca]
logo: [![logo](https://user-images.githubusercontent.com/79248498/163770865-3e220356-90a0-4c3d-bf53-559b07b8f66d.jpg)]
description: [To market this small business]
